version: '3.8'

services:
  pgdb:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: 'dobermann'
      POSTGRES_USER: 'dobermann'
      POSTGRES_PASSWORD: 'dobermann'
    volumes:
      - /Volumes/Finance/postgres-data:/var/lib/postgresql/data
  db:
    image: timescale/timescaledb:latest-pg14
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: 'dobermann'
      POSTGRES_USER: 'dobermann'
      POSTGRES_PASSWORD: 'dobermann'
    volumes:
      - /Volumes/Finance/timescaledb-data:/var/lib/postgresql/data
