version: '3.8'

services:
  db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: 'dobermann'
      POSTGRES_USER: 'dobermann'
      POSTGRES_PASSWORD: 'dobermann'
