version: '3.8'

services:
  db:
    image: timescale/timescaledb:latest-pg14
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: 'dobermann'
      POSTGRES_USER: 'dobermann'
      POSTGRES_PASSWORD: 'dobermann'
    volumes:
      - ~/DobermannVolume/timescaledb-data:/var/lib/postgresql/data
