version: '3.8'

services:
  db:
    image: mongo:5.0
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=dobermann
      - MONGO_INITDB_ROOT_PASSWORD=dobermann
    volumes:
      - ~/dobermann-storage/mongo:/data/db
