[tool.poetry]
name = "dobermann"
version = "0.1.0"
description = "Tools for cryptotrading"
authors = ["Danil Tryapchev <ruthus18@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
asyncpg = "^0.24.0"
tortoise-orm = "^0.17.8"
aerich = "^0.5.8"
pydantic = {version = "^1.8.2", extras = ["dotenv"]}
python-binance = "^1.0.15"
plotly = "^5.3.1"
numpy = {version = "^1.21.2", python = ">=3.9,<3.11"}
pandas = "^1.3.3"
tqdm = "^4.62.3"
aioredis = "^2.0.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
flake8 = "^3.9.2"
isort = "^5.9.3"
jupyterlab = "^3.1.18"
ipdb = "^0.13.9"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
